Задание 3. Создать "скелет" бота
gpb-it-factory/elenberger-telergam-bot pull request #6
Opened 2024-05-15 11:56 UTC by LohmatiyShmel

Реализовал по заданию команду /pong. Также сделал ответы на команды /help и / start. Добавил в readme описание установки, запуска и доступных команд. Очень хочу узнать насколько всё плохо и что стоит переделать в первую очередь.

2024-05-20 05:39 UTC, vaganov-vadim requested changes
Привет! Мне понравился твой PR, сделано здорово. Есть пара комментариев и вопросов, посмотри, пожалуйста.

2024-05-20 05:39 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/captor/CommandCaptor.java
> +    private String messageCaption(Message message) {
Я бы не разбивал на отдельные методы, т. к. в целом одна строка, вполне можно оставить один answer. Но это вкусовщина в какой-то мере.

2024-05-20 05:39 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/commands/CommandAnswerer.java
> +    private Map<String, String> answers;
Нравится использование Map в данном случае, получается расширяемо. И наверное тут должен быть final.

2024-05-20 05:39 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/commands/CommandAnswerer.java
> +    public String needAnAnswer(String command) {
По неймингу не очень понятно, почему именно так называется метод. По текущему названию он как будто должен возвращать boolean.

2024-05-20 05:39 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/commands/CommandAnswerer.java
> +    private String answering(String command) {
Аналогично - пока такой однострочник, то можно добавить в тело основного метода, не вижу смысла выносить в отдельную.

2024-05-20 05:39 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/configuration/BotConfig.java
> +        Map<String,String> answers = new HashMap<>();
Единственное, чего пока не понял - а как мы будем расширять именно поведение? =) Пока что только строки в виде ответов. Или пока просто не заморачиваемся?

2024-05-20 05:39 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/telegrambot/TelegramBot.java
> +    @Value("${bot.Name}")
@Value - не всегда лучший путь прокидывания конфигурации, но я думаю мы ещё об этом поговорим на лекциях :) В целом ок, но надо с осторожностью.

2024-05-20 05:39 UTC, vaganov-vadim commented on src/test/java/com/gpbitfactory/bot/captorTest/CommandCaptorTest.java
> +    public void messageCaptionTest() {
Такие тесты довольно хрупкие, но у нас пока не было лекции по тестам. А в принципе наличие тестов - уже большой плюс, молодец.

2024-05-20 10:37 UTC, LohmatiyShmel commented on src/main/java/com/gpbitfactory/bot/configuration/BotConfig.java
> +        Map<String,String> answers = new HashMap<>();
Я пока сам не понял, если честно. Сделал именно реализацию на уровне пинг-понг и не заморачивался. Как раз пытаюсь в голове уложить как расширяемости добиваются нормальные люди. Как я понял из лекции по API у нас бот как раз должен уметь делать CRUD как минимум, кидаться этими запросами в мидл, и выводить ответ, чтобы пользователь видел, что не  в пустоту тыкал. Я так понимаю, что мне надо сделать интерфейс обработчика сообщений (как я понял это "контроллером" называют), а вот реализации делать в зависимости от их содержания этих сообщений (команда начинающая со /, просто текст, картинка и тд.). Пока хватит реализаций на текст и команды. Надеюсь мысль разумная?

2024-05-20 11:06 UTC, LohmatiyShmel commented on src/main/java/com/gpbitfactory/bot/commands/CommandAnswerer.java
> +    private Map<String, String> answers;
Тут я по какой логике не поставил final. Если в будущем делать возможность расширять список команд в рантайме (те же запрос-ответ), то при расширении HashMap у нас должна поменяться ссылка и final нам покажет на это средний палец. Если такой функционал не планируется, то да. Final будет лучше. Раз уж такого функционала пока нет, а я так понял, что  и не планируется, то да, добавлю в следующем коммите.

2024-05-21 12:19 UTC, LohmatiyShmel commented
Почитал ещё умных книг, сделал интерфейс Command и поменял по неё остальной проект. Добавил логгер простенький (Я так понимаю он нам ещё понадобиться). Жду ответа на такое решение насчет расширяемости

2024-05-21 14:15 UTC, LohmatiyShmel commented on src/main/java/com/gpbitfactory/bot/telegrambot/TelegramBot.java
> +    @Value("${bot.Name}")
Я пока ещё осваиваю Spring и раз нашёл такую вещь в документации, то решил сделать. Если требуется, поищу другие способы

2024-05-22 17:03 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/commands/CommandAnswerer.java
> +    private Map<String, String> answers;
Если хочется менять в рантайме, то и прокидывать обработку надо через какой-то конфиг. Просто подменить мапу будет сложно.

2024-05-22 17:04 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/configuration/BotConfig.java
> +        Map<String,String> answers = new HashMap<>();
Да, понял, думаю когда начнёшь реализовывать именно логику в командах - появятся в голове нужные интерфейсы.

2024-05-22 17:07 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/telegrambot/TelegramBot.java
> +    @Value("${bot.Name}")
Ну я бы сказал так - в нём ничего плохого нет, но лучше тогда прокинуть эти параметры через конструктор и использоваться тот же самый @Value. Здесь проблема не в @Value, а во внедрении зависимостей в поле, что не очень хорошо, лучше почти везде использовать Constructor Injection. Подробнее можно прочитать тут - https://www.baeldung.com/inversion-control-and-dependency-injection-in-spring.

2024-05-22 17:16 UTC, vaganov-vadim requested changes
Привет! С Command стало круче, классно, что ты это нашёл. Но, кажется, есть ещё один путь улучшения. И ещё добавил пару комментов по тестам. Мне очень нравится твой PR, т. к. мы можем многое обсудить и сразу сделать много улучшений, которые тебя прокачают. Так держать!

2024-05-22 17:16 UTC, vaganov-vadim commented on src/main/java/com/gpbitfactory/bot/configuration/BotConfig.java
> +        answers.put("/start", startCommand);
Мне нравится подход с командами. А как на счёт того, чтобы сами названия команд тоже спрятать в классы Command? Тогда не придётся делать никаких ассоциаций руками, всё необходимое знание о команде будет в ней самой, настоящая инкапсуляция =) Как думаешь, получится так сделать?

2024-05-22 17:16 UTC, vaganov-vadim commented on src/test/java/com/gpbitfactory/bot/commandsTest/PingCommandTest.java
> +    public void executeTest() {
Вот это уже отличные тесты.

2024-05-22 17:16 UTC, vaganov-vadim commented on src/test/java/com/gpbitfactory/bot/commandsTest/CommandAnswererTest.java
> +        when(answers.get(anyString())).thenReturn(command);
А стоит ли здесь так увлекаться моками, если можем сами создать какую угодно коллекцию для Answerer? Честно, так будет намного более читаемо и даже тебе удобнее писать тест. Моки - это необходимое зло, где по-другому никак. Но если ты сам можешь создать всё необходимое для теста и проверить поведение, то в них нет смысла.

2024-05-22 17:33 UTC, LohmatiyShmel commented on src/main/java/com/gpbitfactory/bot/configuration/BotConfig.java
> +        answers.put("/start", startCommand);
У меня даже родилась идея как добавлять новые типы команд одной строчкой в конфиге мапы. Благодарю за наводку, доделаю

2024-05-22 17:36 UTC, LohmatiyShmel commented on src/test/java/com/gpbitfactory/bot/commandsTest/CommandAnswererTest.java
> +        when(answers.get(anyString())).thenReturn(command);
Я как раз после лекции прошлой пытаюсь избавиться от желания мокать всё и вся. Укладываю в голове принцип "черного ящика", но вот разок переклинило 😅 . Додумаю более адекватный вариант. Спасибо

2024-05-23 08:13 UTC, LohmatiyShmel commented on src/test/java/com/gpbitfactory/bot/commandsTest/CommandAnswererTest.java
> +        when(answers.get(anyString())).thenReturn(command);
В итоге пришел к тому, что именно свои классы и коллекции я создам ручками перед тестами, а Message как класс самого телеграмма замокаю. Посмотрел количество полей и сколько из них нужно адекватно заполнять для выполнения isCommand и решил не мучаться

2024-05-23 09:02 UTC, LohmatiyShmel commented on src/main/java/com/gpbitfactory/bot/configuration/BotConfig.java
> +        answers.put("/start", startCommand);
Возможно, не до конца понял намек, но, вроде как, стало получше

2024-05-28 05:50 UTC, vaganov-vadim requested changes
Отлично для первой итерации, вливай и развиваем дальше :)

2024-05-28 05:50 UTC, vaganov-vadim approved these changes
Отлично для первой итерации, вливай и развиваем дальше :)

2024-05-28 11:43 UTC, merged